#!/bin/sh -e

GIT_URI="https://github.com/biocoderh/dotfiles.git"

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"
GIT_DIR="$STATE_DIR/dotfiles"
BACKUP_DIR="$STATE_DIR/dotfiles-backup"
WORK_TREE_DIR="$HOME"

mkdir -p "$STATE_DIR/"
git clone --bare "$GIT_URI" "$GIT_DIR"

dotfiles() {
  /usr/bin/git --git-dir="$GIT_DIR/" --work-tree="$WORK_TREE_DIR" "$@"
}

if dotfiles checkout; then
  echo "Checked out dotfiles."
else
  echo "Backing up pre-existing dot files to $BACKUP_DIR"
  dotfiles checkout 2>&1 | awk "/^\t/ { print $1 }" | xargs -I{} sh -c "mkdir -p $BACKUP_DIR/{}; mv $WORK_TREE_DIR/{} $BACKUP_DIR/{}"
  dotfiles checkout
fi

dotfiles config status.showUntrackedFiles no

[ -d "$HOME/.local/bin" ] && chmod +x -R "$HOME/.local/bin"
[ -d "$HOME/.scripts" ] && chmod +x -R "$HOME/.scripts"

[ -f "$HOME/.profile" ] && . "$HOME/.profile"

cat << EOF
dotfiles-install done.

Environment (only Arch Linux):
  full-setup - setup everything except server env.
  repos-setup - setup all repos, paru and run rankmirrors-update.
  base-setup - base environment with some tweaks.
  desktop-setup - graphical environment.
  server-setup - server environment.

Check out README.md or ~/.scripts for more.
EOF
