#!/bin/sh -e

GIT_URI="https://github.com/biocoderh/dotfiles.git"

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"
GIT_DIR="$STATE_DIR/dotfiles"
BACKUP_DIR="$STATE_DIR/dotfiles-backup"
WORK_TREE_DIR="$HOME"

mkdir -p "$STATE_DIR"
git clone --bare "$GIT_URI" "$GIT_DIR"

dotfiles() {
  /usr/bin/git --git-dir="$GIT_DIR/" --work-tree="$WORK_TREE_DIR" "$@"
}

if dotfiles checkout; then
  echo "Checked out dotfiles."
else
  echo "Backing up pre-existing dot files to $BACKUP_DIR"
  mkdir -p "$BACKUP_DIR"
  dotfiles checkout 2>&1 | grep -E "\s+\." | awk "{ print $1 }" | xargs -I{} mv "$WORK_TREE/"{} "$BACKUP_DIR/"{}
  dotfiles checkout
fi

dotfiles config status.showUntrackedFiles no

[ -f "$HOME/.profile" ] && . "$HOME/.profile"
chmod +x -R "$HOME/.local/bin" "$HOME/.scripts"

cat << EOF
dotfiles-install done.

Some additional scripts:
  dotfiles-link - link system files.
  mitigations [on/off] - set kernel boot mitigations param.

Environment (only Arch Linux):
  full-setup - setup everything except server env.
  base-setup - base environment with some tweaks.
  desktop-setup - graphical environment.
  server-setup - server environment.

Check out README.md or ~/.scripts for more.
EOF
