#!/bin/sh -e

if [ -z "$1" ]; then
cat << 'EOF'
Usage: sddm-theme THEME
Set SDDM theme to conf.
EOF
  exit 1
fi

if [ ! -d "/usr/share/sddm/themes/$1" ]; then
  echo "Theme $1 not found."
  exit 1
fi

CONF_FILE="/etc/sddm.conf.d/theme.conf"
sudo mkdir -p "$(dirname $CONF_FILE)"
sudo tee "$CONF_FILE" << END
[Theme]
Current=$1
END

echo "Theme $1 set in $CONF_FILE"
