#!/bin/sh -e

if [ -z "$1" ] || [ -z "$2" ]; then
cat << EOF
Usage: ssh-clone-id KEY REMOTE
Copy private and public keys to remote host, also add them to ssh agent.

Example: ssh-clone-id .ssh/id_ed25519 biocoder@192.168.1.3
EOF
  exit 1
fi

KEY_PATH=$(realpath "$1")
KEY_FILE=$(basename "$1")

REMOTE="$2"
REMOTE_KEY_PATH="$HOME/.ssh/$KEY_FILE"
REMOTE_PUBKEY_PATH="$HOME/.ssh/$KEY_FILE.pub"

USER=$(echo "$2" | cut -d "@" -f 1)
HOME=$(ssh "$2" echo ~)

ssh-copy-id -i "$KEY_PATH.pub" "$REMOTE"

scp "$KEY_PATH" "$KEY_PATH.pub" "$REMOTE:$HOME/.ssh/"

# shellcheck disable=SC2016
CMD='eval $(ssh-agent -s)'
CMD="$CMD ; chmod 400 $REMOTE_KEY_PATH $REMOTE_PUBKEY_PATH"
CMD="$CMD ; ssh-add $REMOTE_KEY_PATH"

ssh -tt -o StrictHostKeyChecking=no "$REMOTE" "$CMD"

echo "ssh-copy-keys done."
