#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -solid "#000000"

for i in /sys/class/hwmon/hwmon*/temp*_input; do 
    if [ "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*}))" = "coretemp: Package id 0" ]; then
        export HWMON_PATH="$i"
    fi
done

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar -r &
