#!/bin/sh -e

PACKAGES=" \
man-db tldr \
zsh tmux neovim \
fzf lf \
"

PREFERED_SHELL="/usr/bin/zsh"

pkgs install "$PACKAGES"

# zsh
if [ "$SHELL" != "$PREFERED_SHELL" ] && [ -f "$PREFERED_SHELL" ]; then
  echo "Changing current shell $SHELL to $PREFERED_SHELL" 
  chsh -s "$PREFERED_SHELL"
fi

# systemd-boot
if [ -f "/boot/loader/loader.conf" ]; then
  sudo sed -i "s/^timeout.*/timeout 0/" /boot/loader/loader.conf

  echo "Setting mitigations off"
  boot-options set mitigations off
fi

# bluetooth
if sudo dmesg | grep -i blue > /dev/null; then
  pkgs install bluez bluez-utils
  sudo systemctl enable --now bluetooth
fi

# Intel
lspci | grep -q 'VGA.*Intel' && pkgs install intel-gpu-tools

if lspci | grep -q 'VGA.*JasperLake'; then
  pkgs install intel-media-sdk
  # https://wiki.archlinux.org/title/intel_graphics#Enable_GuC_/_HuC_firmware_loading
  echo "options i915 enable_guc=2" | sudo tee /etc/modprobe.d/i915.conf
fi

echo "base-setup done."
