#!/bin/sh -e

PACKAGES=" \
flatpak appimagelauncher \
noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-firacode-nerd \
wezterm ttf-nerd-fonts-symbols-mono \
libva-utils corectrl \
firefox chromium \
telegram-desktop webkit2gtk \
qbittorrent \
remmina libvncserver freerdp \
gimp krita xp-pen-tablet \
mpv spotify-launcher sonixd-bin electron22-bin jellyfin-media-player \
"

FLATPAK_PACKAGES=" \
discord \
"

pkgs install "$PACKAGES"
flatpak install "$FLATPAK_PACKAGES"

# virt
[ -c "/dev/kvm" ] && pkgs install qemu-full libvirt virt-manager

# auto-cpufreq
if [ -d "/sys/class/power_supply/BAT0" ]; then
  pkgs install auto-cpufreq
  sudo systemctl enable --now auto-cpufreq
fi

echo "desktop-setup done."
