#!/bin/sh -e

NET_PACKAGES=" \
openssh \
bind nmap \
wget yt-dlp \
proxychains-ng \
iperf3 speedtest-cli \
"

DEV_PACKAGES=" \
lazygit \
docker \
sqlite \
nodejs npm ts-node \
php xdebug \
go \
python-pip python-virtualenv \
"

echo "extra-install done."
case "$1" in
  net)
    pkgs sync
    pkgs install "$NET_PACKAGES"
    ;;
  dev)
    pkgs sync
    pkgs install "$DEV_PACKAGES"
    ;;
  all)
    pkgs sync
    pkgs install "$NET_PACKAGES $DEV_PACKAGES"
    ;;
  *)
cat << 'EOF'
Usage: extra-install [net|dev|all]
Install extra packages.

    net - network packages.
    dev - development packages.
    all - all packages.
EOF
  exit 1 ;;
esac

echo "extra-install done."
