#!/bin/sh -e

PACKAGES=" \
obs-studio-git \
obs-vaapi \
obs-kmsgrab wlrobs \
obs-pipewire-audio-capture-bin \
obs-vkcapture \
obs-ndi-bin \
obs-vban \
obs-audio-monitor \
obs-backgroundremoval \
obs-plugin-tuna-bin \
obs-streamfx \
"

pkgs sync
pkgs install "$PACKAGES"
sudo systemctl enable --now avahi-daemon.service

echo "obs-install done."
