#!/bin/sh -e
# shellcheck disable=SC2068

case "$1" in
  update)
    sudo pacman -Fy
    ;;
  upgrade)
    sudo pacman -Syu --noconfirm

    if [ -x "$(command -v paru)" ]; then
      paru -Syu --noconfirm --sudoloop --skipreview
    elif [ -x "$(command -v yay)" ]; then
      yay -Syu --noconfirm --sudoloop
    fi
    ;;
  install)
    if [ -z "$2" ]; then
cat << 'EOF'
error: no targets specified
usage: pkgs install <package(s)>
EOF
      exit 1
    fi

    shift

    FLAGS="-S"
    CURRENT_TIME=$(date +%s)
    UPDATE_TIME=$(stat -c "%Y" /var/lib/pacman/sync)

    # update if db 24 hours old
    [ $((CURRENT_TIME-UPDATE_TIME)) -gt 86400 ] && FLAGS="-Sy"

    if pacman -Si $@ > /dev/null 2>&1; then
      sudo pacman "$FLAGS" --noconfirm --needed $@
    elif [ -x "$(command -v paru)" ]; then
      paru "$FLAGS" --noconfirm --needed --sudoloop --skipreview $@
    elif [ -x "$(command -v yay)" ]; then
      yay "$FLAGS" --noconfirm --needed --sudoloop $@
    else
cat << 'EOF'
paru or yay not installed.
run `paru-install` to install paru.
EOF
      exit 1
    fi
    ;;
  *)
cat << 'EOF'
usage:  pkgs <operation> [...]
operations:
    pkgs update
    pkgs upgrade
    pkgs install <package(s)>
EOF
  exit 1 ;;
esac
