#!/bin/sh -e

if ! [ -x "$(command -v rankmirrors)" ]; then
  sudo pacman -Sy --noconfirm --needed pacman-contrib
fi

SOURCE="https://archlinux.org/mirrorlist/?protocol=https&use_mirror_status=on"
echo "Using source: $SOURCE"

echo "Starting rankmirrors, it can take a while"
curl -s "$SOURCE" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors - | sudo tee /etc/pacman.d/mirrorlist

echo "rankmirrors-update done."
