#!/bin/sh -e

PACKAGES=""

[ -x "$(command -v rankmirrors)" ] || PACKAGES="$PACKAGES pacman-contrib"
[ -x "$(command -v parallel)" ] || PACKAGES="$PACKAGES parallel"

[ "$PACKAGES" != "" ] && pkgs install "$PACKAGES"

SOURCE="https://archlinux.org/mirrorlist/?protocol=https&use_mirror_status=on"
echo "Using source: $SOURCE"

echo "Starting rankmirrors, it can take a while"
curl -s "$SOURCE" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -p - | sudo tee /etc/pacman.d/mirrorlist

echo "rankmirrors-update done."
