#!/bin/sh -e

PARALLEL_DOWNLOADS="10"
sudo sed -i "s/ParallelDownloads.*/ParallelDownloads = $PARALLEL_DOWNLOADS/" /etc/pacman.conf

rankmirrors-update
paru-install
alhp-install || echo "ALHP unsupported."
chaotic-aur-install

echo "repos-setup done."
