on:
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
	env:
          SHELLCHECK_OPTS: -e SC1090
        with:
          ignore_paths: >-
            .config/zsh
